services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - MONGO_URI=mongodb://mongo:27017/
      - MAIL_SERVER=smtp.gmail.com
      - MAIL_PORT=587
      - MAIL_USE_TLS=true
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
    depends_on:
      - mongo
    volumes:
      - .:/app
    networks:
      - bike-shop-net

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - bike-shop-net

  sonarqube:
    image: sonarqube:community
    ports:
      - "9000:9000"
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_extensions:/opt/sonarqube/extensions
    networks:
      - bike-shop-net

  sonar-scanner:
    image: sonarsource/sonar-scanner-cli:latest  # Використовуємо офіційний образ
    environment:
      - SONAR_HOST_URL=http://sonarqube:9000
      - SONAR_TOKEN=${SONAR_TOKEN}
    volumes:
      - .:/usr/src  # Змінимо на стандартний шлях для sonar-scanner
    working_dir: /usr/src  # Встановлюємо робочий каталог
    depends_on:
      - sonarqube
    networks:
      - bike-shop-net

volumes:
  mongo_data:
  sonarqube_data:
  sonarqube_logs:
  sonarqube_extensions:

networks:
  bike-shop-net:
    driver: bridge